<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5e9f05b2db26551dc82a14421ceefa0c
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Faker\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Faker\\' => 
        array (
            0 => __DIR__ . '/..' . '/fzaninotto/faker/src/Faker',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5e9f05b2db26551dc82a14421ceefa0c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5e9f05b2db26551dc82a14421ceefa0c::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
